travis:
  secure:
    BINSTAR_TOKEN: A6TmyOcnukqGPXG7XliwIadOktfs3aB7nBe6SGEceFORnGaKPtg9M3ZNHHhPK4ETB/oIfog341lkd4CSbd7wbpWjJQa+T61iCsKLW8yin9xo5u/+STyNQ5tWmK0udYpugid2JbsP8rJvEdIUYuOh2sOm+4t0cJVwHo8bhMeKEWtQUl03mVX42tU03ysqqIMPidGjLIdl9lYw1EQG21iGtcT49ADBWhlWR6icFUJf4fbhKBwXTEX6ymisU2kECcGlN3tZm1OTQQqw6PEV8NN7DbkXJz3LQdxQxA2hG/S6jVuCbwG0xs1w4UCo14jAuy+zTuFs/JJfJQHmV7XxYtgYfQoXL/242xOumZDfLe+grtkxj23SXF2Yd24Jmb6PiCBldqIadW3qcJortnAC0sKZgqV19VTW9i68QRN9ynRSzeJulVEG4VJOJWNA6EpoZAVYUXCSrqrAjsmSHo5e5aKFvIQ9Z2Dubj//+2JZy1VGmsBw2Rti1hnoBjD17oewiE2fFKr/oayjoXo5XLbnz0lML3ri0bcyU2qJOtTTVbnje7/c4KMKVp6mA29qeV+w78fwRlrdLbyjkgg4LvCntVJndT9eqfjIVlbVCEpQN20dTkV8PpUT2M2kxVxgetd6du9Bq+qNRwEt3vuYbagI0/zS8LrFegW683WLyl0SNWU/puU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
